#!/usr/bin/env bash

if [ "${EUID}" -gt 0 ]; then
	echo "Please run as root"
	exit 1
fi

chmod 0755 tpm2Hook
cp tpm2Hook /etc/initramfs-tools/hooks/tpm2
chmod 0755 /etc/initramfs-tools/hooks/tpm2
cp tpm2Hook /usr/share/initramfs-tools/hooks/tpm2
chmod 0755 /usr/share/initramfs-tools/hooks/tpm2
chown 0:0 /etc/initramfs-tools/hooks/tpm2 /usr/share/initramfs-tools/hooks/tpm2

mkdir -p /etc/initramfs/post-update.d/
cp bootChain-update /etc/initramfs/post-update.d/
chmod +x /etc/initramfs/post-update.d/bootChain-update

mkdir -p /usr/local/var/tpm-manager || exit 1
chmod 0500 /usr/local/var/tpm-manager || exit 1
chown 0:0 /usr/local/var/tpm-manager || exit 1
cd /usr/local/var/tpm-manager || exit 1

touch secret.bin
chmod 0400 secret.bin
dd if=/dev/urandom of=secret.bin bs=32 count=1 conv=sync

# Pulls out the name of the LUKS encrypted drive.
drive=$(blkid | grep LUKS | grep -Pow "^/[A-Za-z0-9/]+")
cryptsetup luksAddKey $drive secret.bin

# Pulls out the UUID of the LUKS encrypted drive.
luks=$(blkid | grep LUKS |  grep -Po "(?<= UUID\=\")[a-z0-9-]+")

# Edits /etc/crypttab to include the new secret and the keyscript
sed -i "/$luks/s/none/\/usr\/local\/var\/tpm-manager\/secret.bin/g" /etc/crypttab
sed -i "/$luks/s/$/\,keyscript=/usr/local/bin/passphrase-from-tpm/g" /etc/crypttab

tpm2_clear
tpm2_pcrread sha1:0,2,3,7 -o pcrs.bin
tpm2_createpolicy --policy-pcr -l sha1:0,2,3,7 -f pcrs.bin --policy policy.digest
tpm2_createprimary -c primary.context
tpm2_create -u obj.pub -r obj.priv -C primary.context -L policy.digest --attributes "noda|adminwithpolicy|fixedparent|fixedtpm" -i secret.bin
tpm2_evictcontrol -c load.context
