#!/bin/sh
PREREQ=""
prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions

tpm2_pcrevent 12 /proc/cmdline
$(sbverify --cert /usr/local/var/bootChain/db.crt /boot/efi/EFI/BOOT/BOOTX64.EFI) | tpm2_pcrevent 12
tpm2_pcrevent 12 /usr/local/var/bootChain/db.crt
tpm2_pcrread | tpm2_pcrevent 12
$(sbverify --list /boot/efi/EFI/BOOT/BOOTX64.EFI) | tpm2_pcrevent 12
tpm2_pcrread | tpm2_pcrevent 12
